### ISSUE TITLE
Support for syncing/loading OCI Tarball bundles into a registry?

### ISSUE THREAD

**Issue by prologic** [mqasimsarfraz/imagesync#1]
As per the title, can this tool support loading up OCI Tarballs, for example what `docker save <image>` outputs?

**Comment by mqasimsarfraz** [comment]
@prologic thanks for the issue. Currently, there isn't any support for OCI Tarballs but for understanding you want to push an OCI tar to `--dest` registry ?

**Comment by prologic** [comment]
Yes 👌

**Comment by mqasimsarfraz** [comment]
Cool. I will have a look into! :)

**Comment by mqasimsarfraz** [comment]
@prologic I added the support to sync different sources. If you want to sync `docker save` output you can use [docker-archive](https://github.com/mqasimsarfraz/imagesync#docker-archive) and if you have an OCI archive (multi-platform supported) you will need to use [oci-archive](https://github.com/mqasimsarfraz/imagesync#oci-archive).  I have added all the examples. Please let me know if it work fine for you now! :)
